apiVersion: v1
entries:
  secrets-store-csi-driver-provider-aws:
  - apiVersion: v2
    appVersion: 0.0.6
    created: "2021-11-03T01:02:29.244197+03:00"
    description: A Helm chart to install AWS Secrets Manager and Config Provider for
      Secret Store CSI Driver.
    digest: 8ef76e37167594d7f938eca689e1313fb708a17b0aa385cc3d0d3de28b22b746
    name: secrets-store-csi-driver-provider-aws
    sources:
    - https://github.com/roman-avseenko/secrets-store-csi-driver-provider-aws
    urls:
    - secrets-store-csi-driver-provider-aws-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2021-11-03T01:02:29.243958+03:00"
    description: A Helm chart to install AWS Secrets Manager and Config Provider for
      Secret Store CSI Driver.
    digest: 96c2b4bb960dab13cc7a911d099ba14db5b25e1b64ec612bec3d5ccc431c8274
    name: secrets-store-csi-driver-provider-aws
    sources:
    - https://github.com/roman-avseenko/secrets-store-csi-driver-provider-aws
    urls:
    - secrets-store-csi-driver-provider-aws-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2021-11-03T01:02:29.243749+03:00"
    description: A Helm chart to install AWS Secrets Manager and Config Provider for
      Secret Store CSI Driver.
    digest: 888e9696e6e03e586c31113dbccd6f8863276ae90eccc7a9d64a51bc4c8714ba
    name: secrets-store-csi-driver-provider-aws
    sources:
    - https://github.com/roman-avseenko/secrets-store-csi-driver-provider-aws
    urls:
    - secrets-store-csi-driver-provider-aws-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2021-11-03T01:02:29.243482+03:00"
    description: A Helm chart to install AWS Secrets Manager and Config Provider for
      Secret Store CSI Driver.
    digest: 8e061b99d523c18c4997ed3f5cb14eb1ac6bfdeedcb9187088b78110aa348191
    name: secrets-store-csi-driver-provider-aws
    sources:
    - https://github.com/roman-avseenko/secrets-store-csi-driver-provider-aws
    urls:
    - secrets-store-csi-driver-provider-aws-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v1
    created: "2021-11-03T01:02:29.243262+03:00"
    description: A Helm chart to install AWS Secrets Manager and Config Provider for
      Secret Store CSI Driver.
    digest: fc6daec9c515d28853da687e8b8ae7c1cf992aec78b215ff2f1848ba2eb096f1
    name: secrets-store-csi-driver-provider-aws
    urls:
    - secrets-store-csi-driver-provider-aws-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v1
    created: "2021-11-03T01:02:29.243038+03:00"
    description: A Helm chart to install AWS Secrets Manager and Config Provider for
      Secret Store CSI Driver.
    digest: 5f78688a29c1de1b24950492ca00e5dec4ab58f54cf13409201307a0f82a1a8b
    name: secrets-store-csi-driver-provider-aws
    urls:
    - secrets-store-csi-driver-provider-aws-0.0.1.tgz
    version: 0.0.1
generated: "2021-11-03T01:02:29.242663+03:00"
