apiVersion: v1
entries:
  secrets-store-csi-driver-provider-aws:
  - apiVersion: v1
    created: "2021-11-02T22:35:24.042552+03:00"
    description: A Helm chart to install AWS Secrets Manager and Config Provider for
      Secret Store CSI Driver.
    digest: 5f78688a29c1de1b24950492ca00e5dec4ab58f54cf13409201307a0f82a1a8b
    name: secrets-store-csi-driver-provider-aws
    urls:
    - secrets-store-csi-driver-provider-aws-0.0.1.tgz
    version: 0.0.1
generated: "2021-11-02T22:35:24.042208+03:00"
